version: "3.8"

services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mi_mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"
